// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0pKRoL8iUJo6dsLRIbNGc6jx5UHO-fA',
    appId: '1:461071135746:web:222c06262935b32a47231b',
    messagingSenderId: '461071135746',
    projectId: 'happy-paws-fb',
    authDomain: 'happy-paws-fb.firebaseapp.com',
    storageBucket: 'happy-paws-fb.appspot.com',
    measurementId: 'G-W4TWHSRV46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYh2jKducVqzi3vKcRsyF64gPFrOS9eh4',
    appId: '1:461071135746:android:795613c5f351e1eb47231b',
    messagingSenderId: '461071135746',
    projectId: 'happy-paws-fb',
    storageBucket: 'happy-paws-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GvCPBcUuQyf6loucl2ACu8IKdEM3RHM',
    appId: '1:461071135746:ios:f27b597c063cbfc247231b',
    messagingSenderId: '461071135746',
    projectId: 'happy-paws-fb',
    storageBucket: 'happy-paws-fb.appspot.com',
    iosBundleId: 'com.example.happypaws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7GvCPBcUuQyf6loucl2ACu8IKdEM3RHM',
    appId: '1:461071135746:ios:f27b597c063cbfc247231b',
    messagingSenderId: '461071135746',
    projectId: 'happy-paws-fb',
    storageBucket: 'happy-paws-fb.appspot.com',
    iosBundleId: 'com.example.happypaws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0pKRoL8iUJo6dsLRIbNGc6jx5UHO-fA',
    appId: '1:461071135746:web:e5fb50d357c2f6e047231b',
    messagingSenderId: '461071135746',
    projectId: 'happy-paws-fb',
    authDomain: 'happy-paws-fb.firebaseapp.com',
    storageBucket: 'happy-paws-fb.appspot.com',
    measurementId: 'G-XD15HF3EZG',
  );
}
