version: '3'
services:
#mssql docker
  happypaws-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=IDKdks9119!
      - MSSQL_PID=Developer
    ports:
      - 4444:1433
    expose:
      - 1433
    networks:
      - happypawsnet

  happypaws-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Main=Server=happypaws-sql, 4444;Database=happypaws-docker;User=rania;Password=IDKdks9119!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
    networks:
      - happypawsnet
    links:
      - happypaws-sql
    depends_on:
      - happypaws-sql
      
networks:
  happypawsnet:
    driver: bridge      